#ifndef COMPUTER_ENGINE_H
#define COMPUTER_ENGINE_H
// ### Draft for Chess Engine ###

/*
Have a computer make decisions for a one player game. Computer is always black.
//Intercontinental Ballistic Missile Variation
  - have a basic/generic opening that starts autogenerated based of which pawns are started.
  - take up optimial locations first (control over center, develop main pieces)
  - have a risk assumption on taking pieces, i.e which piece is worth more but also play more conservative for higher value pieces.
  - go for easy pieces to take
  - always try to protect the king
*/
#include <stdlib.h>
#include <stdio.h>
#include <time.h>
#include <stdbool.h>
#include "PrintingBoard.h" // Make sure this includes definitions used below
#include "PieceMovementB.h"
#include "PieceMovementW.h"
#define BOARD_SIZE 8


